dist: trusty

language: java

jdk:
  - oraclejdk8

addons:
  sonarqube:
      token:
            secure: J5AQ8Yowyqp/amuybUIwXF0wBlXjBMKbpwl4SrnddteZSyTOaKeW6fPeNaVE+hbyuRf9/Q0apmwTW/6QpwybjuONkEnY1xJob7zHIymMQ+CUC4WyMD179q1Gr9eoIzwOYNnwYnBrMdQnWpzOxLq3EJdTs1Hm+N6XP3gA0YM2MH/ic0ssNablnSbNDfb8cCjg8oNqwzIJefQ99/nzrCfEa/U+Yg1I1h87WA94DUkIb4rW6EOX6DyAJapopzdZUqSubBSyPzGWFGbCIkRkQn29Mh7Vmwnbw6jpJcGQa/lVezkxm4qJwk0SeyCDeBUnaGye59Zk/60v5pemAa7+yMXVjDwoiVfJ6JbpYXkACDJDvzalzw65aQER7LbNxAEytW+ANMZwABoAV+k0zJyFTxhi+reN/iPsusHuc47YLtyIl1swJEBIx7ZSLg3+2pqI7sXWGSHBsbgR+JbmtH+2i36YcX8BKvGcJ2ATphq5BwthwET6W9O8GE5BijaakHWlzE+IUrBZqJtm/gOjaSSu7ZVckpoIn/V83NFIHcCkiBh5FMxfRYRyqB1TVA313U+0ZxUCzxUsBRIVuxw4l6V7Oq8L+cEEAWuZ7DQxGYXO4bmc8P5syDmYp4bvW7Xncbu0DEf9AcQIQBgnAnjdPBmmodWO0gDy2A3B31nVqzzmAYNhzV8=
      github_token:
            secure: Rz2fjYQzR68qATM5yAy5CsL2M6ikIdxzJ5IPSfXfSAkvc1lkGwFnVyo/DUxQRUfu8iLyTCGMn2Y6nLu40rsp28LWVYiWUV40f8l4fxCLXWrFsoq1vphPP01MhxxpajrDKaIZr4f5zglyA3uW73gQuZg36xprgCYyEyRlOk5HmznPD56DFW7TsJ1oFu6DPI2AhvjR1mL2F6n13rgEchJszuB1lF6Mg4jpOXjF7mjkHAmqQOd383S1pbBVxu86Zwxs8SQakL4FNFTVh4Ju/kjHvxu+DIVzSSB2aBOQiZOE0F5EPHE6a9yZBnS6EHyZ9DwfET9ohitfm9i8Yiegxa0beI6AIRWW+CpsdEQII9Jw68A+ilc1BMBkqqvXvdkArUQKuR0HryAA8eUfAuUkxai5mQxsWFbVZEFyqXQtdLZTGmwDoqtcTyi9bsXSugFcFKbGC89lLufrqQWCs0sF20HYNukqhNSqCvRkEzWVS762yYVivpcHV2GEPViEdZkJCD2gS47GmZk4FBSGrgjHhJ8KrUZIEYqtAK6paRZVPD9SGjhR1T+XtH03GcilaYOBhAZbCek4ETJp4j8nvHgd3HJqNSHQs4f8YbRfWUMpHeUE0g2+kJ9CR/ja7XhDilo9mkmn6al88RZ1Wt7hvpuw1xgGkQoXGtS2kGjxozd6TQUa/Ak=


cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar

script:
- mvn clean test
#  - mvn clean test jacoco:report coveralls:report
  - sonar-scanner -X